### ISSUE TITLE
Realizar el diagrama espina de pescado

### ISSUE THREAD

**Issue by MarianaHenao0707** [MarianaHenao0707/equipo3_fbm_ppi2020#2]
![diagrama de pescado](https://user-images.githubusercontent.com/66319171/85893137-e65d6500-b7b7-11ea-9e79-bb18b305d54e.jpg)

**Comment by manuela4** [comment]
![gggg](https://user-images.githubusercontent.com/66319459/84184824-a5ddb780-aa53-11ea-8694-6e32fe45668f.png)

**Comment by marthaduque** [comment]
llevarlo a la wiki y revisar las causas

**Comment by marthaduque** [comment]
deben poner las causas en las espinas del pescado y no las consecuencias.
