### ISSUE TITLE
Declarar de la situación del problema

### ISSUE THREAD

**Issue by MarianaHenao0707** [MarianaHenao0707/equipo3_fbm_ppi2020#4]
Las personas de la comuna 5 de Medellín, no saben diferenciar los tipos de residuos o desechos, no saben en qué momento y cómo separarlos al momento de sacarlos, debido a que estas personas no están bien informadas y no tienen el suficiente conocimiento sobre qué es, cómo se clasifican y se separan dichos residuos o desechos, lo que está causando problemas de contaminación, enfermedades, malos olores y la obstrucción del paso.

**Comment by marthaduque** [comment]
mejorar la redacción de acuerdo a lo indicado
